---
- name: "Install common packages"
  hosts: localhost
  become: yes
  tasks:
    - name: Install persistent / runtime deps / phpize deps
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apt-utils
        - autoconf
        - bc
        - bison
        - build-essential
        - bzip2
        - ca-certificates
        - file
        - flex
        - g++
        - gcc
        - git
        - imagemagick
        - libaspell-dev
        - libbz2-dev
        - libc-client2007e-dev
        - libc-dev
        - libcurl4-openssl-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgd2-xpm-dev
        - libgpg-error-dev
        - libjpeg-dev
        - libmagickwand-dev
        - libmcrypt-dev
        - libmcrypt4
        - libmhash-dev
        - libpng-dev
        - libpq-dev
        - libreadline6-dev
        - librecode0
        - libsnmp-dev
        - libsqlite3-0
        - libsqlite3-dev
        #- libt1-dev
        - libxml2
        - make
        #- php5-gd
        - libphp-adodb
        - re2c
        - uuid-dev
        - vim
        - wget
        - zlib1g-dev
        - apache2
        - elinks
        #- apache2-threaded-dev
        #- apache2.2-common
